sudo: required

language: php

services:
  - docker

before_install:
- ls -lahR ./var/
- ./ci/prepare.sh
- ls -lahR ./var/
- docker build -t yr-bdd:full docker/full

script:
- ./bin/docker test
- ls -lahR ./var/
