<?php

namespace AppBundle\Repository;

/**
 * ChirpRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ChirpRepository extends \Doctrine\ORM\EntityRepository
{
}
